# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28c778c66a7a0d3e4b8e63cf4affb0d7789d4fc842c9274c780f1e7a052bed054dbabace9cb7b3ae123cf961ac695ab4be6e5427e0180fc7aca2c558f61a73ad

test:
  secret_key_base: edf0b418ab6151ce4831f587a8c14a520b5f63661397ccef0273471873a45574ff60c0edbbbc22b64c1f1ddf9223144c706d76ad6233452f6fbcebcecfcece39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
